### ISSUE TITLE
Insertion of dummy values into the tables

### ISSUE THREAD

**Issue by ImanolSP** [F-Urquizo/Repositorio_Reto#9]
- Use Case name: DB testing
- Related Requirements: Creation of tables and relations between tables
- Goal in context: To insert values into the tables to find out if the tables are well done and everything works
- Preconditions: Having the tables and relations between this tables well done
- Successful end condition: The values are inserted correctly and the queries are fetched correctly
- Fail end condition: The values aren't inserted correctly and the queries aren't fetched correctly
- Primary actors: DB developer
- Secondary actors: N/A
- Triggers: N/A
- Main Flow:N/A
- Extensions: N/A

**Comment by A09271** [comment]
Creado el .sql con datos coerentes
